spring:
  profiles:
    active: eureka2
  application:
    name: spring-eureka-service
    index: ${spring.application.name}:${HOST:${random.value}}

server:
  port: 8762

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30